const COUNTRIES_DATA_REQUEST = "COUNTRIES_DATA_REQUEST"
const COUNTRIES_DATA_SUCCESS = "COUNTRIES_DATA_SUCCESS"
const COUNTRIES_DATA_FAILURE = "COUNTRIES_DATA_FAILURE"

export default {
    COUNTRIES_DATA_REQUEST,
    COUNTRIES_DATA_SUCCESS,
    COUNTRIES_DATA_FAILURE
}