const COUNTRIES_DATA_REQUEST = "COUNTRIES_DATA_REQUEST"
const COUNTRIES_DATA_SUCCESS = "COUNTRIES_DATA_SUCCESS"
const COUNTRIES_DATA_FAILURE = "COUNTRIES_DATA_FAILURE"

const GET_ALL_COUNTRIES_DATA_REQUEST = "GET_ALL_COUNTRIES_DATA_REQUEST"
const GET_ALL_COUNTRIES_DATA_SUCCESS = "GET_ALL_COUNTRIES_DATA_SUCCESS"
const GET_ALL_COUNTRIES_DATA_FAILURE = "GET_ALL_COUNTRIES_DATA_FAILURE"

const GET_SPECIFIC_COUNTRIES_DATA_REQUEST = "GET_SPECIFIC_COUNTRIES_DATA_REQUEST"
const GET_SPECIFIC_COUNTRIES_DATA_SUCCESS = "GET_SPECIFIC_COUNTRIES_DATA_SUCCESS"
const GET_SPECIFIC_COUNTRIES_DATA_FAILURE = "GET_SPECIFIC_COUNTRIES_DATA_FAILURE"

export default {
    COUNTRIES_DATA_REQUEST,
    COUNTRIES_DATA_SUCCESS,
    COUNTRIES_DATA_FAILURE,

    GET_ALL_COUNTRIES_DATA_REQUEST,
    GET_ALL_COUNTRIES_DATA_SUCCESS,
    GET_ALL_COUNTRIES_DATA_FAILURE,

    GET_SPECIFIC_COUNTRIES_DATA_REQUEST,
    GET_SPECIFIC_COUNTRIES_DATA_SUCCESS,
    GET_SPECIFIC_COUNTRIES_DATA_FAILURE
}